import {
  Layers,
  Bot,
  MessageSquareText,
  Users,
  Cpu,
  Handshake,
  Target,
  Code2,
  Palette,
  Brain,
  UserCheck,
  Rocket,
  Settings2,
  MessageSquare,
  Lightbulb,
  CheckCircle,
  GraduationCap,
  Landmark,
  ShoppingCart,
  Stethoscope,
  Building2,
  Briefcase,
  MapPin,
  Clock,
  Zap,
  Heart,
  TrendingUp,
  ArrowRight,
  Star,
  Quote,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  layers: Layers,
  bot: Bot,
  'message-square-text': MessageSquareText,
  users: Users,
  cpu: Cpu,
  handshake: Handshake,
  target: Target,
  code2: Code2,
  palette: Palette,
  brain: Brain,
  'user-check': UserCheck,
  rocket: Rocket,
  settings2: Settings2,
  'message-square': MessageSquare,
  lightbulb: Lightbulb,
  'check-circle': CheckCircle,
  'graduation-cap': GraduationCap,
  landmark: Landmark,
  'shopping-cart': ShoppingCart,
  stethoscope: Stethoscope,
  building2: Building2,
  briefcase: Briefcase,
  'map-pin': MapPin,
  clock: Clock,
  zap: Zap,
  heart: Heart,
  'trending-up': TrendingUp,
  'arrow-right': ArrowRight,
  star: Star,
  quote: Quote,
}

export function getIcon(name: string | undefined | null): LucideIcon | null {
  if (!name) return null
  return iconMap[name.toLowerCase()] || null
}
